---
- hosts: all
  become: true

  tasks:
  - name: Download Java JRE
    get_url:
      url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.rpm
      dest: /opt/jre-8u60-linux-x64.rpm
      headers: 'Cookie: gpw_e24=http://www.oracle.com/; oraclelicense=accept-securebackup-cookie'

  - name: install Java JRE rpm from a local file
    yum:
      name: /opt/jre-8u60-linux-x64.rpm
      state: present

  - name: Download Java JDK
    get_url:
      url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm
      dest: /opt/jdk-8u60-linux-x64.rpm
      headers: 'Cookie: gpw_e24=http://www.oracle.com/; oraclelicense=accept-securebackup-cookie'

  - name: Install Java JDK rpm from a local file
    yum:
     name: /opt/jdk-8u60-linux-x64.rpm
     state: present



     ---
- name: Install docker
  hosts: jenkins
  become: true

  tasks:
    - name: Install docker
      yum_repository:
        name: docker
        description: repo for docker
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: no

    - name: docker install
      command:
        cmd: yum install docker-ce --no-best -y

    - name: Install pip
      yum:
        name: python-pip
        state: latest

    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
